# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Install-Module -Name PSScriptAnalyzer -Scope CurrentUser -Force
    failOnStderr: true
    pwsh: true
  name: Install_PSScriptAnalyzer
  
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Invoke-ScriptAnalyzer -Path Invoke-VsBuild\Invoke-VsBuild.psm1
    failOnStderr: true
    pwsh: true
  name: Run_PSScriptAnalyzer
  
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)'
    artifact: 'Invoke-VsBuild'
    publishLocation: 'pipeline'

