trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Install-Module -Name PSScriptAnalyzer -Scope CurrentUser -Force
    failOnStderr: true
    pwsh: true
  name: Install_PSScriptAnalyzer

- task: PowerShell@2
  condition: eq('$(UpdateModuleVersion)', 'true')
  inputs:
    filePath: 'eng\Update-Version.ps1'
    failOnStderr: true
    pwsh: true
  displayName: Update Module Version
  
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Invoke-ScriptAnalyzer -Path Invoke-VsBuild\Invoke-VsBuild.psd1
    failOnStderr: true
    pwsh: true
  name: Run_PSScriptAnalyzer

- task: PowerShell@2
  condition: eq('$(UpdateModuleVersion)', 'true')
  inputs:
   targetType: inline
   pwsh: true
   script: |
     git add Invoke-VsBuild\Invoke-VsBuild.psd1
     git commit -m "Update Module Version to $(ENV:UpdatedModuleVersion)"
     git push https://github.com/vatsan-madhavan/Invoke-VsBuild master

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Invoke-ScriptAnalyzer -Path Invoke-VsBuild\Invoke-VsBuild.psd1
    failOnStderr: true
    pwsh: true
  displayName: Run_PSScriptAnalyzer on updated Module

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)'
    artifact: 'Invoke-VsBuild'
    publishLocation: 'pipeline'
  displayName: Uplaod scripts to Artifacts

